// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var SERVICES = [
  {
    name: "AI Customer Service Agent",
    channels: ["WhatsApp", "Email", "Website live chat widget"],
    description: "One AI agent across WhatsApp, email, and a live chat widget on your own website. Answers FAQs, qualifies leads, drafts on-brand email replies and follow-ups, escalates only when a human needs to step in."
  },
  {
    name: "Lead Capture & Follow-Up",
    description: "Captures leads from any source and follows up automatically over WhatsApp and email until they book or buy."
  },
  {
    name: "Booking & Appointment Automation",
    description: "Customers self-book on WhatsApp in seconds. Automated reminders reduce no-shows."
  },
  {
    name: "Missed Call Text-Back",
    description: "When you can't answer, GrowMatic auto-sends the caller a WhatsApp message within seconds \u2014 a missed call becomes a live conversation instead of a lost customer."
  },
  {
    name: "Client Dashboard",
    description: "A private, always-up-to-date link showing upcoming bookings and leads. No extra app, no separate login."
  },
  {
    name: "Review & Reputation Manager",
    description: "Asks happy customers for Google reviews at the right moment. AI drafts on-brand replies for one-tap approval."
  },
  {
    name: "Social Media Automation",
    description: "Generates, schedules, and posts to Facebook and Instagram consistently."
  },
  {
    name: "Custom AI Workflows",
    description: "Any repetitive process mapped and automated: invoices, onboarding, reporting."
  }
];
var get_services_default = defineTool({
  name: "list_services",
  title: "List GrowMatic services",
  description: "Returns the full catalog of AI automation services GrowMatic builds for South African businesses.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SERVICES, null, 2) }],
    structuredContent: { services: SERVICES }
  })
});

// src/lib/mcp/tools/get-pricing.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var PLANS = [
  {
    name: "Starter",
    setup: "R4,999 once-off",
    monthly: "R999/month",
    features: [
      "1 AI automation system",
      "AI agent on WhatsApp, email & website chat widget",
      "2-week average setup",
      "30-day onboarding support",
      "Monthly performance report"
    ]
  },
  {
    name: "Growth",
    setup: "R9,999 once-off",
    monthly: "R1,999/month",
    mostPopular: true,
    features: [
      "3 AI automation systems",
      "AI agent on WhatsApp, email & website chat widget",
      "Lead capture & follow-up across all channels",
      "Booking system included",
      "Priority support + monthly strategy review"
    ]
  },
  {
    name: "Enterprise",
    setup: "Custom",
    monthly: "Custom",
    features: [
      "Unlimited automations",
      "AI agent on WhatsApp, email & website chat widget",
      "Full business audit + dedicated account manager",
      "Staff training included",
      "SLA and uptime guarantees"
    ]
  }
];
var get_pricing_default = defineTool2({
  name: "get_pricing",
  title: "Get GrowMatic pricing",
  description: "Returns GrowMatic's current pricing plans (Starter, Growth, Enterprise) with setup fee, monthly fee, and included features.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(PLANS, null, 2) }],
    structuredContent: { plans: PLANS }
  })
});

// src/lib/mcp/tools/book-call.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var WHATSAPP_NUMBER = "27671082665";
var book_call_default = defineTool3({
  name: "get_booking_link",
  title: "Get strategy call booking link",
  description: "Returns a pre-filled WhatsApp link to book a free strategy call with GrowMatic. Optionally include a short note about the caller's business or interest to pre-fill the message.",
  inputSchema: {
    note: z.string().max(300).optional().describe("Optional short note about the business or interest (max 300 chars).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: ({ note }) => {
    const message = note?.trim() ? `Hi! I'd like to book a free strategy call. ${note.trim()}` : "Hi! I'd like to book a free strategy call.";
    const url = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
    return {
      content: [{ type: "text", text: url }],
      structuredContent: { url, whatsappNumber: `+${WHATSAPP_NUMBER}` }
    };
  }
});

// src/lib/mcp/tools/get-faqs.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var FAQS = [
  {
    q: "How long does setup take?",
    a: "Most Starter systems go live within 2 weeks. Growth systems typically take 3-4 weeks depending on scope."
  },
  {
    q: "Which channels does the AI agent work on?",
    a: "One agent across WhatsApp, email, and a live chat widget embedded on your own website."
  },
  {
    q: "Do you work with businesses outside South Africa?",
    a: "GrowMatic is based in South Africa and focused on the SA market, but the systems work anywhere."
  },
  {
    q: "Can I cancel anytime?",
    a: "Yes. Monthly plans are month-to-month with no lock-in."
  }
];
var get_faqs_default = defineTool4({
  name: "list_faqs",
  title: "List FAQs",
  description: "Returns frequently asked questions about GrowMatic's service, setup, and pricing.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(FAQS, null, 2) }],
    structuredContent: { faqs: FAQS }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "growmatic-mcp",
  title: "GrowMatic",
  version: "0.1.0",
  instructions: "Tools for GrowMatic \u2014 a South African AI automation agency. Use `list_services` to see what GrowMatic builds, `get_pricing` for plans and prices, `list_faqs` for common questions, and `get_booking_link` to generate a WhatsApp link for booking a free strategy call.",
  tools: [get_services_default, get_pricing_default, get_faqs_default, book_call_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
