// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/get-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
var SERVICES = [
  {
    name: "24/7 Customer Response",
    channels: ["WhatsApp", "Email", "Website live chat widget"],
    description: "Answers every customer in seconds across WhatsApp, email and your website \u2014 day or night \u2014 and only brings you in when a real person is genuinely needed. No enquiry ever goes cold, and you look bigger and more professional."
  },
  {
    name: "Lead Management",
    description: "Captures every enquiry from any source and follows up automatically over WhatsApp and email until the customer books, buys, or clearly says no \u2014 so more of the leads you already pay for turn into paying customers."
  },
  {
    name: "Effortless Booking & Appointments",
    description: "Customers self-book in seconds and get friendly reminders before every appointment \u2014 a fuller diary, far fewer no-shows, and zero admin on your side."
  },
  {
    name: "Never Miss a Lead (Missed-Call Recovery)",
    description: "The moment a call is missed, GrowMatic sends the caller a friendly WhatsApp within seconds \u2014 a missed call becomes a live conversation instead of a lost customer."
  },
  {
    name: "Business Intelligence Dashboard",
    description: "A private, always-current view of every upcoming booking and new lead in one place. No extra app, no separate login \u2014 you always know exactly where the business stands."
  },
  {
    name: "Reputation & Reviews",
    description: "Asks happy customers for a Google review at exactly the right moment and drafts an on-brand reply to every review for one-tap approval \u2014 more 5-star reviews, more trust, more new customers."
  },
  {
    name: "Marketing on Autopilot",
    description: "Creates, schedules and posts to Facebook and Instagram consistently on your behalf \u2014 your business stays visible and top-of-mind without you opening the app."
  },
  {
    name: "Business Process Optimisation",
    description: "Maps and streamlines the repetitive work behind the scenes \u2014 quotes, invoices, onboarding, reporting \u2014 so there's less manual admin, fewer mistakes, and more time to grow."
  }
];
var get_services_default = defineTool({
  name: "list_services",
  title: "List GrowMatic services",
  description: "Returns the full catalog of business growth and automation solutions GrowMatic provides for South African businesses.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SERVICES, null, 2) }],
    structuredContent: { services: SERVICES }
  })
});

// src/lib/mcp/tools/get-pricing.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
var PLANS = [
  {
    name: "Growth Starter",
    setup: "R5,000 once-off",
    monthly: "R3,500/month",
    mostPopular: true,
    features: [
      "24/7 customer response on WhatsApp, email & website chat \u2014 replies in seconds",
      "Every enquiry captured and followed up automatically",
      "Bookings & appointments straight into your diary",
      "Missed calls recovered instantly by WhatsApp",
      "Monthly results report"
    ]
  },
  {
    name: "Business Autopilot",
    setup: "R7,500 once-off",
    monthly: "R4,500/month",
    features: [
      "Everything in Growth Starter",
      "Automatic quoting & invoice follow-ups",
      "Reminders that cut no-shows",
      "Live business dashboard included",
      "Priority support + monthly growth review"
    ]
  },
  {
    name: "Custom Growth Solution",
    setup: "From R15,000 once-off",
    monthly: "Custom",
    features: [
      "Tailored solution mapped to your exact workflow",
      "Full business review + dedicated account manager",
      "Unlimited custom processes streamlined",
      "Staff training included",
      "Service-level & uptime guarantees"
    ]
  }
];
var get_pricing_default = defineTool2({
  name: "get_pricing",
  title: "Get GrowMatic pricing",
  description: "Returns GrowMatic's current pricing packages (Growth Starter, Business Autopilot, Custom Growth Solution) with setup fee, monthly fee, and included features. Start with a 30-day pilot \u2014 month-to-month, cancel anytime.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(PLANS, null, 2) }],
    structuredContent: { plans: PLANS }
  })
});

// src/lib/mcp/tools/book-call.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var WHATSAPP_NUMBER = "27671082665";
var book_call_default = defineTool3({
  name: "get_booking_link",
  title: "Get consultation booking link",
  description: "Returns a pre-filled WhatsApp link to book a free business consultation with GrowMatic. Optionally include a short note about the caller's business or interest to pre-fill the message.",
  inputSchema: {
    note: z.string().max(300).optional().describe("Optional short note about the business or interest (max 300 chars).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: ({ note }) => {
    const message = note?.trim() ? `Hi! I'd like to book a free business consultation. ${note.trim()}` : "Hi! I'd like to book a free business consultation.";
    const url = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
    return {
      content: [{ type: "text", text: url }],
      structuredContent: { url, whatsappNumber: `+${WHATSAPP_NUMBER}` }
    };
  }
});

// src/lib/mcp/tools/get-faqs.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
var FAQS = [
  {
    q: "How long until it's up and running?",
    a: "Most businesses on Growth Starter are live within 2 weeks. Business Autopilot and the Custom Growth Solution typically take 3-4 weeks depending on scope. Start with a 30-day pilot \u2014 month-to-month, cancel anytime."
  },
  {
    q: "Which channels does it cover?",
    a: "Your customers are looked after across WhatsApp, email, and a live chat widget on your own website \u2014 all from one place."
  },
  {
    q: "Do you work with businesses outside South Africa?",
    a: "GrowMatic is based in South Africa and focused on the SA market, but the systems work anywhere."
  },
  {
    q: "Can I cancel anytime?",
    a: "Yes. Monthly plans are month-to-month with no lock-in."
  }
];
var get_faqs_default = defineTool4({
  name: "list_faqs",
  title: "List FAQs",
  description: "Returns frequently asked questions about GrowMatic's service, setup, and pricing.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(FAQS, null, 2) }],
    structuredContent: { faqs: FAQS }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "growmatic-mcp",
  title: "GrowMatic",
  version: "0.1.0",
  instructions: "Tools for GrowMatic \u2014 a South African business growth and automation partner that helps businesses win more customers, respond faster and cut manual admin. Use `list_services` to see the solutions GrowMatic provides, `get_pricing` for plans and prices, `list_faqs` for common questions, and `get_booking_link` to generate a WhatsApp link for booking a free business consultation.",
  tools: [get_services_default, get_pricing_default, get_faqs_default, book_call_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
